"""
OpenDoc — Pydantic schemas for request/response models.
"""

from pydantic import BaseModel, Field
from typing import Optional


class AnalyzeRequest(BaseModel):
    """Request body for the /analyze endpoint."""
    repo_url: str = Field(
        ...,
        description="Full GitHub repository URL",
        examples=["https://github.com/tiangolo/fastapi"],
    )
    provider: str = Field(
        default="groq",
        description="LLM Provider (e.g., groq, openai, anthropic, google)",
    )
    model: Optional[str] = Field(
        default=None,
        description="Specific model to use (optional)",
    )
    api_key: str = Field(
        ...,
        description="API key for the chosen provider",
    )
    report_mode: str = Field(
        default="client",
        description="Type of report mode (client, learning, understanding, portfolio, custom)",
    )
    custom_sections: Optional[list[str]] = Field(
        default=None,
        description="List of enabled sections for custom report mode",
    )


class AnalyzeLocalRequest(BaseModel):
    """Request body for the /analyze-local endpoint (VS Code extension)."""
    project_name: str = Field(
        ...,
        description="Workspace folder name",
        examples=["my-project"],
    )
    folder_structure: str = Field(
        ...,
        description="Newline-separated file tree of the project",
    )
    files: dict[str, str] = Field(
        default_factory=dict,
        description="Map of filename → content for key project files",
    )
    provider: str = Field(
        default="groq",
        description="LLM Provider (e.g., groq, openai, anthropic, google)",
    )
    model: Optional[str] = Field(
        default=None,
        description="Specific model to use (optional)",
    )
    api_key: str = Field(
        ...,
        description="API key for the chosen provider",
    )
    report_mode: str = Field(
        default="client",
        description="Type of report mode (client, learning, understanding, portfolio, custom)",
    )
    custom_sections: Optional[list[str]] = Field(
        default=None,
        description="List of enabled sections for custom report mode",
    )



class ProductDirection(BaseModel):
    """Structured product direction assessment."""
    strongest_direction: str = ""
    highest_impact_next_step: str = ""
    biggest_technical_risk: str = ""
    most_impressive_aspect: str = ""
    most_underrated_feature: str = ""


class ReportData(BaseModel):
    """Structured AI-generated report — opinionated senior engineer analysis."""
    repo_name: str = ""
    repo_url: str = ""
    report_mode: str = ""
    executive_summary: str = ""
    what_it_actually_is: str = ""
    core_strengths: list[str] = Field(default_factory=list)
    engineering_assessment: str = ""
    scope_vs_execution: str = ""
    product_direction: Optional[ProductDirection] = None
    biggest_risks: list[str] = Field(default_factory=list)
    most_impressive_aspect: str = ""
    recommended_next_step: str = ""
    portfolio_assessment: str = ""
    developer_intelligence: str = ""
    final_verdict: str = ""
    
    # Review & Learning fields
    project_maturity: str = ""
    engineering_patterns: list[str] = Field(default_factory=list)
    architecture_observations: list[str] = Field(default_factory=list)
    repeated_concepts: list[str] = Field(default_factory=list)
    learning_areas: list[str] = Field(default_factory=list)



class AnalyzeResponse(BaseModel):
    """Response body for the /analyze endpoint."""
    success: bool = True
    report: Optional[ReportData] = None
    error: Optional[str] = None


class PDFRequest(BaseModel):
    """Request body for the /generate-pdf endpoint."""
    report: ReportData


class TrackedFile(BaseModel):
    """Activity tracker details for a single file in the session."""
    filename: str
    imports: list[str] = Field(default_factory=list)
    functions: list[str] = Field(default_factory=list)
    action: str = Field(..., description="Action taken: opened or edited")


class DevNotesRequest(BaseModel):
    """Request body for the /generate-dev-notes endpoint."""
    project_name: str = Field(..., description="Name of the workspace folder")
    tracked_files: list[TrackedFile] = Field(default_factory=list)
    provider: str = Field(default="groq", description="LLM Provider")
    model: Optional[str] = Field(default=None, description="Model to use")
    api_key: str = Field(..., description="API key")


class DevNotesData(BaseModel):
    """Structured development notes fields generated by the AI."""
    what_was_worked_on: list[str] = Field(default_factory=list)
    concepts_used: list[str] = Field(default_factory=list)
    possible_goals: list[str] = Field(default_factory=list)
    architecture_changes: list[str] = Field(default_factory=list)
    learning_topics: list[str] = Field(default_factory=list)


class DevNotesResponse(BaseModel):
    """Response body for the /generate-dev-notes endpoint."""
    success: bool = True
    dev_notes: Optional[DevNotesData] = None
    error: Optional[str] = None

